name: autologin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cookie_jar: ^4.0.8
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: ^1.5.0
  http_interceptor: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
