name: autologin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cookie_jar: ^4.0.8
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: ^1.5.0
  http_interceptor: ^2.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true # Generate for Android (can also be a file name like "ic_launcher")
  ios: true # Generate for iOS
  image_path: "assets/autoLoginLogo.png" # <-- This is the path to your icon
  min_sdk_android: 21 # Optional: for adaptive icon support

